### ISSUE TITLE
Problem with combining json files 

### ISSUE THREAD

**Issue by jalm03** [baieric/chatstats#7]
I have some trouble running this command because I don't know how to run the command exactly, "python3 combinejson.py", where do I put the direction of the chat folder? because if I put it "Enter the path of your json file(s): <here>" without the "<>" it doesn't work. 

Thank you!

**Comment by baieric** [comment]
Hi, did you figure this out? I updated the code today so that the combinejson step is done for you behind the scenes when you run the chatstats step.
