### ISSUE TITLE
problem running chatstats.py

### ISSUE THREAD

**Issue by ZmeyGorynychh** [baieric/chatstats#8]
Hi! 
I have a problem running the progam. 
When I run it, it lists all of the JSON parts, but after a few seconds, it stops and i get : 

Traceback (most recent call last):
  File "chatstats.py", line 225, in <module>
    main(sys.argv)
  File "chatstats.py", line 207, in main
    messages = clean_data(pd.DataFrame(json_data["messages"]))
  File "chatstats.py", line 67, in clean_data
    data['game'] = data['content'].str.contains(constants.GAME_REGEX, na=False)
AttributeError: module 'scipy.optimize._highs.constants' has no attribute 'GAME_REGEX'

I have absolutely no idea what it means :')
Thanks ~

**Comment by baieric** [comment]
Hi, thanks for your interest in ChatStats! It looks like there is a problem with the imports. `constants` should refer to the chatstats constants, but the code is interpreting it as constants from `scipy.optimize_highs`. If you're new to coding that might not be super helpful, but unfortunately I won't have time to look into it further for a bit.

**Comment by baieric** [comment]
Hi, I renamed the `constants` module, and I think it should work now. You need to get the latest version of chatstats. Hit me up if you need help!

**Comment by ZmeyGorynychh** [comment]
Hi! It all works perfectly now, thanks a lot. That's awesome stuff :)
